[tool.poetry]
name = "pylinalg"
version = "0.3.0"
description = "Linear algebra utilities for Python"
authors = ["Korijn van Golen <korijn@gmail.com>"]
license = "MIT"
homepage = "https://github.com/pygfx/pylinalg"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
numpy = ">=1.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
flake8 = "^5.0.4"
black = "^22.8.0"
flake8-black = "^0.3.3"
flake8-import-order = "^0.18.1"
pytest-cov = "^3.0.0"
twine = { version = "^4.0.1", python = "<4.0.0" }
pytest-watcher = { version = "^0.2.3", python = "<4.0.0" }

[build-system]
requires = ["poetry>=1.2.0"]
build-backend = "poetry.core.masonry.api"
